# x-www-form-urlencoded:
# json


openapi: 3.0.0
info:
  title: Task Manager
  description: Task Manager is developed for managing tasks of multiple users.
  version: 0.1.1
paths:
  /manikalai:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                mobileNumber:
                  type: string
              # required:
      # - name
      # - email
      responses:
        '200':
          description: Resturn success message

